apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-version-2
  labels:
    app: nginx
    version: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: "2"
  template:
    metadata:
      labels:
        app: nginx
        version: "2"
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: init-busybox
        image: busybox:1.28
        command: ['sh', '-c', 'echo "version 2" > /work-dir/index.html']
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      volumes:
      - name: workdir
        emptyDir: {}   
