apiVersion: v1
kind: Pod
metadata:
  labels:
    probe: liveness
  name: nginx-liveness
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2  
    livenessProbe:
      exec:
        command:
        - ls
      initialDelaySeconds: 5
      periodSeconds: 5

