apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-liveness-delay
  name: nginx-liveness-delay
spec:
  containers:
  - image: nginx:latest
    name: nginx-liveness-delay
    resources: {}
    livenessProbe:
      exec:
        command:
        - ls
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
