apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-readiness
  name: nginx-readiness
spec:
  containers:
  - image: nginx:latest
    name: nginx-readiness
    resources: {}
    ports:
    - name: http-port
      containerPort: 80
      hostPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: http-port 
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
