apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-test
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    max:
      memory: 512Mi
    min:
      memory: 256Mi      
    type: Container

