apiVersion: v1
kind: Pod
metadata:
  name: pod-limit-range-test 
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 1024Mi
