apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvcnew
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard 
