apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-capabilities-pod
  name: nginx-capabilities-pod
spec:
  containers:
  - image: nginx
    name: nginx-capabilities-pod
    resources: {}
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]   
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
