apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-user-id-pod
  name: nginx-user-id-pod
spec:
  securityContext:
    runAsUser: 101  
  containers:
  - image: nginx
    name: nginx-user-id-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
