apiVersion: v1
kind: Pod
metadata:
  name: busybox-pvc
spec:
  containers:
    - name: busybox
      image: busybox
      args: ["/bin/sh", "-c", "sleep 3600"]  
      volumeMounts:
      - mountPath: "/etc/foo"
        name: pvc-volume
  volumes:
    - name: pvc-volume
      persistentVolumeClaim:
        claimName: mypvc
