apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: consumer
  name: consumer
  namespace: secret-ops
spec:
  containers:
  - image: nginx:latest
    name: consumer
    resources: {}
    volumeMounts:
    # name must match the volume name below
    - name: secret-volume
      mountPath: /var/app
      readOnly: true 
  dnsPolicy: ClusterFirst
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
  restartPolicy: Never
status: {}
