apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-quota-demo-again
  name: nginx-quota-demo-again
spec:
  containers:
  - image: nginx
    name: nginx-quota-demo-again
    resources: {}
    resources:
      requests:
        memory: "1Gi"
        cpu: "0.5"
      limits:
        memory: "2Gi"
        cpu: "1"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
