apiVersion: v1
kind: ServiceAccount
metadata:
  name: myuser
---
apiVersion: v1
kind: Secret
metadata:
  name: myuser-secret
  annotations:
    kubernetes.io/service-account.name: myuser
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-sa
  name: nginx-sa
spec:
  serviceAccountName: myuser
  automountServiceAccountToken: false
  containers:
  - image: nginx:latest
    name: nginx-sa
    resources: {}
    volumeMounts:
    - name: secret-volume
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: secret-volume
    secret:
      secretName: myuser-secret
status: {}
