apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-quota-demo
  name: nginx-quota-demo
spec:
  containers:
  - image: nginx
    name: nginx-quota-demo
    resources: {}
    resources:
      requests:
        memory: "3Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "3"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
