apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-2
  name: nginx-2
spec:
  containers:
  - image: nginx:latest
    name: nginx-2
    resources: {}
    envFrom:
      - configMapRef:
          name: anotherone 
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
