apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-resource-req-lim
  name: nginx-resource-req-lim
spec:
  containers:
  - image: nginx
    name: nginx-resource-req-lim
    resources: {}
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
