apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-id
  name: nginx-id
spec:
  securityContext:
    runAsUser: 101
  containers:
  - image: nginx
    name: nginx-id
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
