apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-1
  name: nginx-1
spec:
  containers:
  - image: nginx:latest
    name: nginx-1
    resources: {}
    env:
    - name: option
      valueFrom:
        configMapKeyRef:
          name: options
          key: var5
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
