apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-configs-pod
  name: nginx-configs-pod
spec:
  containers:
  - image: nginx
    name: nginx-configs-pod
    envFrom:
      - configMapRef:
          name: anotherone      
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
