apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: consumer-vol
  name: consumer-vol
  namespace: secret-ops
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
  containers:
  - image: nginx:1.14.2
    name: consumer-vol
    resources: {}
    volumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: "/var/app"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
